#ifndef KEY_H
#define KEY_H

namespace td {

/* ------------------------------------------------------------------------- */

namespace Key {
  enum {
    LEFT = 1000,
    RIGHT,
    UP,
    DOWN,
    ESCAPE,
    PAGEUP,
    PAGEDOWN,
    HOME,
    ZERO = '0',
    ONE = '1',
    TWO = '2',
    THREE = '3',
    FOUR = '4',
    FIVE = '5',
    SIX = '6',
    SEVEN = '7',
    EIGHT = '8',
    NINE = '9',
    A_LOWER = 'a',
    B_LOWER = 'b',
    C_LOWER = 'c',
    D_LOWER = 'd',
    E_LOWER = 'e',
    F_LOWER = 'f',
    G_LOWER = 'g',
    H_LOWER = 'h',
    I_LOWER = 'i',
    J_LOWER = 'j',
    K_LOWER = 'k',
    L_LOWER = 'l',
    M_LOWER = 'm',
    N_LOWER = 'n',
    O_LOWER = 'o',
    P_LOWER = 'p',
    Q_LOWER = 'q',
    R_LOWER = 'r',
    S_LOWER = 's',
    T_LOWER = 't',
    U_LOWER = 'u',
    V_LOWER = 'v',
    W_LOWER = 'w',
    X_LOWER = 'x',
    Y_LOWER = 'y',
    Z_LOWER = 'z',
    A_UPPER = 'A',
    B_UPPER = 'B',
    C_UPPER = 'C',
    D_UPPER = 'D',
    E_UPPER = 'E',
    F_UPPER = 'F',
    G_UPPER = 'G',
    H_UPPER = 'H',
    I_UPPER = 'I',
    J_UPPER = 'J',
    K_UPPER = 'K',
    L_UPPER = 'L',
    M_UPPER = 'M',
    N_UPPER = 'N',
    O_UPPER = 'O',
    P_UPPER = 'P',
    Q_UPPER = 'Q',
    R_UPPER = 'R',
    S_UPPER = 'S',
    T_UPPER = 'T',
    U_UPPER = 'U',
    V_UPPER = 'V',
    W_UPPER = 'W',
    X_UPPER = 'X',
    Y_UPPER = 'Y',
    Z_UPPER = 'Z',
    PIPE = '|',
    LESS_THAN = '<',
    GREATER_THAN = '>',
    CARET = '^',
    PERIOD = '.',
    EXCLAMATION = '!',
    LEFT_SQUARE_BRACKET = '[',
    RIGHT_SQUARE_BRACKET = ']',
    LEFT_CURLY_BRACE = '{',
    RIGHT_CURLY_BRACE = '}',
    COMMA = ',',
    PLUS = '+',
    MINUS = '-',
    EQUALS = '='
  };
};

/* ------------------------------------------------------------------------- */

}

#endif
